### ISSUE TITLE
Creates a sparse file on NTFS which does not write zeros to disk

### ISSUE THREAD

**Issue by WindowsVista42** [Ian-Parberry/stompdisk#1]
I was doing some testing with your program and found that if you read the file in HxD it shows up as being all zeros, but if you read the contents of the disk instead, you find that there is no such section that has been zeroed out (tested with 6 gig files on an 8 gig flash drive). While the run time of the program was excellent, it was also far faster than my flash drive should be able to do (near-instant execution on a flash drive with ~7.5MB/s write speed). After doing some further testing; formatting my flash drive to NTFS or FAT32, writing some random data, then testing the program, I found that this program only works as intended on FAT32 file systems, and after some digging, here is what I found:

NTFS has the concept of a "sparse file" ([relevant section](https://docs.microsoft.com/en-us/windows/win32/fileio/sparse-files#:~:text=When%20a%20write,the%20read%20operation.)) which are essentially any large file (typically anything larger than an image) where different portions of the file can exist on different sections of a disk. NTFS sparse files also allow the file system to allocate a large chunk of the drive without actually having to write out that data. From my understanding when SetFilePointerEx ([relevant section](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfilepointerex#:~:text=Note%20that%20it,intervening%20bytes%20uninitialized)) and SetEndOfFile ([relevant section](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setendoffile#:~:text=The%20SetEndOfFile%20function%20can%20be%20used%20to%20truncate%20or%20extend%20a%20file.%20If%20the%20file%20is%20extended%2C%20the%20contents%20of%20the%20file%20between%20the%20old%20end%20of%20the%20file%20and%20the%20new%20end%20of%20the%20file%20are%20not%20defined.)) are called, Windows does not automatically write to this created file and is instead just allocating the space. The Windows docs also state that the data written to by SetEndOfFile is undefined, and in the case of an NTFS file system, it is creating a sparse file that allocates and "writes zeros", but doesn't actually write any zeros. Sparse files however will report the relevant sections that are zeroed out as being zeros, even though no data has been written. I would imagine from a performance/longevity standpoint this is a huge boost, but it also means that to write data to the drive, you have to explicitly write data out to the drive.

There might be something I'm missing here or another of doing this, but it appears that the current method being used doesn't work on NTFS file systems.

**Comment by Ian-Parberry** [comment]
Thanks for catching that!  I guess I’ll have to go back to writing all zeros. ☹
Ian

_______________________________________________________________________
From the keyboard of Ian Parberry, PhD. http://ianparberry.com<http://ianparberry.com/>
Professor, Dept. of Computer Science and Engineering, University of North Texas
“Bureaucracy is expanding to meet the needs of an expanding bureaucracy.”

From: Sean Moulton ***@***.***>
Sent: Thursday, June 16, 2022 1:03 AM
To: Ian-Parberry/stompdisk ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [Ian-Parberry/stompdisk] Creates a sparse file on NTFS which does not write zeros to disk (Issue #1)


I was doing some testing with your program and found that if you read the file in HxD it shows up as being all zeros, but if you read the contents of the disk instead, you find that there is no such section that has been zeroed out (tested with 6 gig files on an 8 gig flash drive). While the run time of the program was excellent, it was also far faster than my flash drive should be able to do (near-instant execution on a flash drive with ~7.5MB/s write speed). After doing some further testing; formatting my flash drive to NTFS or FAT32, writing some random data, then testing the program, I found that this program only works as intended on FAT32 file systems, and after some digging, here is what I found:

NTFS has the concept of a "sparse file" (relevant section<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fwin32%2Ffileio%2Fsparse-files%23%3A~%3Atext%3DWhen%2520a%2520write%2Cthe%2520read%2520operation.&data=05%7C01%7CIan.Parberry%40unt.edu%7Cecd1551ffccb4c7e489a08da4f5dceeb%7C70de199207c6480fa318a1afcba03983%7C0%7C0%7C637909561605206791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cWbhOcvoDf%2FDhiJkPALbABsVvWPZUoCiCuHa0e3az0s%3D&reserved=0>) which are essentially any large file (typically anything larger than an image) where different portions of the file can exist on different sections of a disk. NTFS sparse files also allow the file system to allocate a large chunk of the drive without actually having to write out that data. From my understanding when SetFilePointerEx (relevant section<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fwin32%2Fapi%2Ffileapi%2Fnf-fileapi-setfilepointerex%23%3A~%3Atext%3DNote%2520that%2520it%2Cintervening%2520bytes%2520uninitialized&data=05%7C01%7CIan.Parberry%40unt.edu%7Cecd1551ffccb4c7e489a08da4f5dceeb%7C70de199207c6480fa318a1afcba03983%7C0%7C0%7C637909561605206791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2y%2FZtACPkWtoYAPzKmfoa2pJSPu6znvl6L2I5kohaEU%3D&reserved=0>) and SetEndOfFile (relevant section<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fwin32%2Fapi%2Ffileapi%2Fnf-fileapi-setendoffile%23%3A~%3Atext%3DThe%2520SetEndOfFile%2520function%2520can%2520be%2520used%2520to%2520truncate%2520or%2520extend%2520a%2520file.%2520If%2520the%2520file%2520is%2520extended%252C%2520the%2520contents%2520of%2520the%2520file%2520between%2520the%2520old%2520end%2520of%2520the%2520file%2520and%2520the%2520new%2520end%2520of%2520the%2520file%2520are%2520not%2520defined.&data=05%7C01%7CIan.Parberry%40unt.edu%7Cecd1551ffccb4c7e489a08da4f5dceeb%7C70de199207c6480fa318a1afcba03983%7C0%7C0%7C637909561605363052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DDBn1CbbLuq2nXnPx%2Fr2Ecb8c2Ho%2FTHI3e92lgk802k%3D&reserved=0>) are called, Windows does not automatically write to this created file and is instead just allocating the space. The Windows docs also state that the data written to by SetEndOfFile is undefined, and in the case of an NTFS file system, it is creating a sparse file that allocates and "writes zeros", but doesn't actually write any zeros. Sparse files however will report the relevant sections that are zeroed out as being zeros, even though no data has been written. I would imagine from a performance/longevity standpoint this is a huge boost, but it also means that to write data to the drive, you have to explicitly write data out to the drive.

There might be something I'm missing here or another of doing this, but it appears that the current method being used doesn't work on NTFS file systems.

**Comment by Ian-Parberry** [comment]
The code has now been updated to write pseudo-random bytes. It's now quite slow, since speed is now limited by disk transfer rate,

**Comment by Ian-Parberry** [comment]
Issue is now closed.
